version: '3.8'

services:
  prometheus-dingtalk-hook:
    image: ghcr.io/nicoorz/prometheus-dingtalk-hook:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./templates:/app/templates:ro
