services:
  prometheus-dingtalk-hook:
    image: ghcr.io/nicoorz/prometheus-dingtalk-hook:latest
    ports:
      - "8080:8080"
    volumes:
      - ./config.yml:/etc/promethues-DingTalk-Hook/config.yml:ro
      - ./templates:/etc/promethues-DingTalk-Hook/templates:ro
    command: ["-config", "/etc/promethues-DingTalk-Hook/config.yml"]
